Repository Demohack2022/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#1 quizgame
  quizgame.py
Labels: hacktoberfest-accepted

#2 made some changes
  omkar.py
Labels: hacktoberfest-accepted

#3 Ui game in python
  game.py
Labels: hacktoberfest-accepted

#4 Electronic Shop inventory and management system using java
  electronic_shop.java
  proj.c
Labels: hacktoberfest-accepted

#6 Created Snake Game Main
  Snake Game
Labels: hacktoberfest-accepted

#7 Game Main Module
  Game Body
Labels: hacktoberfest-accepted

#8 Simple ATM Code
  atm.c
Labels: hacktoberfest-accepted

#9 Static Website for Hostipal and medical chain
  IP PROJECT.zip
Labels: hacktoberfest-accepted

#10 fact.py
  fact.py
Labels: hacktoberfest-accepted

#11 Bat Symbol Graphic Using Python
  Dark Knight.py
Labels: hacktoberfest-accepted

#12 Create login.html
  login.html
  login_style.css
  signup.html
Labels: hacktoberfest-accepted

#13 LOGIN System Using php and DB
  loginsystem/forgetpass.php
  loginsystem/login.php
  loginsystem/loginid.sql
  loginsystem/logout.php
  loginsystem/signup.php
  loginsystem/welcome.php
Labels: hacktoberfest-accepted

#14 Measurement Conversion System using php and has db
  Measurement_conversion with database.zip
Labels: hacktoberfest-accepted

#15 Dynamic method dispatch in java
  DynamicMethodDispatch.java
Labels: hacktoberfest-accepted

#16 simple_interest.c
  simple_interest.c
Labels: hacktoberfest-accepted

#18 Blog Page using HTML, CSS and JS
  blog/blog.html
  blog/design.css
  blog/java.js
Labels: hacktoberfest-accepted

#19 MineSweeper using C++
  Minesweeper.cpp.cpp
Labels: hacktoberfest-accepted

#20 Added another method to find factorial
  SETrelations.c
  fact.py
  rockPaperScissor.java
Labels: hacktoberfest-accepted

#21 button added
  glowing_button/css/styles.css
  glowing_button/index.html
Labels: hacktoberfest-accepted

#22 College Website
  MINI Project college website/about us.html
  MINI Project college website/chem.html
  MINI Project college website/contact us.html
  MINI Project college website/courses.html
  MINI Project college website/cs.html
  MINI Project college website/department.html
  MINI Project college website/ele.html
  MINI Project college website/images/college.jpg
  MINI Project college website/images/faculty.jpg
  MINI Project college website/images/kadam.jpg
  MINI Project college website/images/logo.png
  MINI Project college website/it.html
  MINI Project college website/mech.html
  MINI Project college website/sports.html
  MINI Project college website/web.html
  images/college.jpg
  images/faculty.jpg
  images/kadam.jpg
  images/logo.png
Labels: hacktoberfest-accepted

#23 TicTacTo Program Using C++
  SUDOKU.CPP
  TICTACTO.CPP
Labels: hacktoberfest-accepted

#24 minor changes
  SETpowerSet.cpp
  SETrelations.c
  simple_interest.c
  simple_interest.exe
Labels: hacktoberfest-accepted

#25 Change Text Color on Button Click
  change color.html
Labels: hacktoberfest-accepted

#31 Changes file in dark knight
  Dark Knight.py
  matrix.py
Labels: hacktoberfest-accepted

#28 product_website.html
  product_website.html
Labels: hacktoberfest-accepted

#29 login_pg.html
  login_pg.html
Labels: hacktoberfest-accepted

#32 Piano in C++
  PIANO.CPP
Labels: hacktoberfest-accepted

#30 TexFlip
  TextFlip
Labels: hacktoberfest-accepted

#34 Added Ip address validator
  ipValidator.html
Labels: hacktoberfest-accepted

#36 Asteroid game using C++
  Asteroid.c.cpp
Labels: hacktoberfest-accepted

#40 Restaurant management system
  restaurant.ipynb
Labels: hacktoberfest-accepted

#41 Added New Project (Ripple Button)
  Ripple Button Effect/index.html
  Ripple Button Effect/style.css
Labels: hacktoberfest-accepted

#42 Quizegame.java
  Quizegame.java
Labels: hacktoberfest-accepted

#44 Doodle Jump using C++
  DoodleJump.c.cpp
Labels: hacktoberfest-accepted

#45 Multiplication-table program
  Displaying multiplication table of entered number.py
Labels: hacktoberfest-accepted

#46 Angle Finder Project Python
  angle-finder.py
Labels: hacktoberfest-accepted

#47 Create Client.java file in Quiz Project
  Quiz Project/Client.java
Labels: hacktoberfest-accepted

#38 Added Insertion and Bubble Sort Algorithms
  Bubble_sort.cpp
  insertion_sort.cpp
Labels: hacktoberfest-accepted

#35 Prime or not
  primeornot.c
Labels: hacktoberfest-accepted

#49 added bmi calculator
  BMI_calculator/bmi.py
  BMI_calculator/ftstomsConvert_BMI_calc.py
  BMI_calculator/lbtoKgConvert_BMI_calc.py
Labels: hacktoberfest-accepted

#50 create aditi.py
  aditi.py
Labels: hacktoberfest-accepted

#51 newtoncradel added
  newton-cradel/css/styles.css
  newton-cradel/index.html
Labels: hacktoberfest-accepted

#62 Automobile Website added
  RR-AUTOMOBILES/css/styles.css
  RR-AUTOMOBILES/img/cardesign-01.jpg
  RR-AUTOMOBILES/img/cardesign-02.jpg
  RR-AUTOMOBILES/img/cardesign-03.jpg
  RR-AUTOMOBILES/img/cardesign-04.jpg
  RR-AUTOMOBILES/img/cardesign-05.jpg
  RR-AUTOMOBILES/img/cardesign-06.jpg
  RR-AUTOMOBILES/img/customer-01.jpg
  RR-AUTOMOBILES/img/customer-02.jpg
  RR-AUTOMOBILES/img/customer-03.jpg
  RR-AUTOMOBILES/img/hero-bg.jpg
  RR-AUTOMOBILES/img/home-about-img.jpg
  RR-AUTOMOBILES/img/icon.png
  RR-AUTOMOBILES/img/image.jpg
  RR-AUTOMOBILES/img/logo.png
  RR-AUTOMOBILES/index.html
  RR-AUTOMOBILES/js/app.js
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#63 Create Electricitybill.c
  TASK-Management/Electricitybill.c
Labels: hacktoberfest-accepted, hacktoberfest

#64 Create Password-Generator.java
  Password-Generator.java
Labels: hacktoberfest-accepted, hacktoberfest

#65 A Simple Python CALCULATOR
  calculator.py
Labels: hacktoberfest-accepted, hacktoberfest

#67 squarert.py
  squarert.py
Labels: hacktoberfest-accepted, hacktoberfest

#69 quiz.py
  quiz.py
Labels: hacktoberfest-accepted

#71 New request
  Registration Form/.vscode/settings.json
  Registration Form/bg.jpg
  Registration Form/index.html
  Registration Form/style.css
Labels: hacktoberfest-accepted

#70 Create matrixMultiplication.c
  matrixMultiplication.c
Labels: hacktoberfest-accepted

#72 code for reversing nodes in k groups of LL
  Reverse_nodes_in_k_groups.cpp
Labels: hacktoberfest-accepted

#68 leapyear.py
  leapyear.py
Labels: hacktoberfest-accepted

#73 calendar.py
  calendar.py
Labels: hacktoberfest-accepted

#74 Created YouTube_Search/main.py
  YouTube_Search/main.py
Labels: hacktoberfest-accepted

#79 Website added
  Portfolio Website/assets/background.gif
  Portfolio Website/assets/icon.png
  Portfolio Website/assets/logo.png
  Portfolio Website/assets/me.jpg
  Portfolio Website/assets/menu.jpg
  Portfolio Website/css/fonts.css
  Portfolio Website/css/normalize.css
  Portfolio Website/css/style.css
  Portfolio Website/index.html
  Portfolio Website/js/app.js
Labels: hacktoberfest-accepted

#80 Create clock_project
  clock_project
Labels: hacktoberfest-accepted

#81 Create electricity_bill.c
  electricity_bill.c
Labels: hacktoberfest-accepted, hacktoberfest

#82 Elec_bill.c
  TASK-Management/Elec_bill.c
Labels: hacktoberfest-accepted, hacktoberfest

#83 FaceGame is added.
  Contributors/facegame.py
Labels: hacktoberfest-accepted, hacktoberfest

#84 Create index.html
  Registration form design/index.html
Labels: hacktoberfest-accepted

#86 Create calc.py
  Simple Calculator/calc.py
Labels: hacktoberfest-accepted

#88 Added code for to do list
  todolist.html
Labels: hacktoberfest-accepted

#94 game in py
  snakegame.py
Labels: hacktoberfest-accepted

#92 create calc
  calc.py
Labels: hacktoberfest-accepted

#96 Egg catcher game
  eggcatcher.py
Labels: hacktoberfest-accepted

#98 Hangman
  hangman.py
Labels: hacktoberfest-accepted

#99 Create a HotelManage in C
  HotelManage.c
Labels: hacktoberfest-accepted

#100 Create billing java
  billing.java
Labels: hacktoberfest-accepted

#101 added a story program in python
  convert.py
  story.py
Labels: hacktoberfest-accepted

#103 Added ChristmasTree Pattern in Java
  java_patterns/ChristmasTree.java
Labels: hacktoberfest-accepted

#104 Added DiamondShape in Java
  java_patterns/DiamondShape
Labels: hacktoberfest-accepted

#105 Arithmetic calculator in Python
  arithmetic-calculator.py
Labels: hacktoberfest-accepted

#106 Create Balloon_Shooting_Game.cpp
  Balloon_Shooting_Game.cpp
Labels: hacktoberfest-accepted

#108 added BMI calculator using js
  BMI/index.html
  BMI/main.js
  BMI/stylesheet.css
Labels: hacktoberfest-accepted

#109 Create wordguess.py
  wordguess.py
Labels: hacktoberfest-accepted
